version: "3.1"

services:
  db:
    image: postgres:14-alpine
    environment:
            POSTGRES_DB: "${DATABASE_NAME}"
            POSTGRES_USER: "${DATABASE_USER}"
            POSTGRES_PASSWORD: "${DATABASE_PASS}"

    
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'

  myadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ale@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80   
    depends_on:
      - db  